In [1]:
import pandas as pd
from datetime import timedelta, datetime
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [2]:
COLUMN_NAMES = ['SYMBOL','SERIES','DATE','PREV_CLOSE','OPEN_PRICE','HIGH_PRICE','LOW_PRICE','LAST_PRICE',
                'CLOSE_PRICE','AVG_PRICE','TTL_TRD_QNTY','NO_OF_TRADES','DELIV_QTY','DELIV_PER','DELIV_VALUE',
                '5DDeVA','%Change_In_Price','%Change_In_Deliv_vs_AVG','Intraday_volume']

In [3]:
Company_list = ['3MINDIA','AARTIDRUGS','AARTIIND','AAVAS','ABB','ABCAPITAL','ABFRL','ACC','ACCELYA','ACE','ADANIENT',
                'ADANIPORTS','ADFFOODS','ADVENZYMES','AEGISCHEM','AHLUCONT','AIAENG','AJANTPHARM','AKZOINDIA','ALEMBICLTD',
                'ALKEM','ALKYLAMINE','ALLCARGO','ALOKINDS','AMARAJABAT','AMBER','AMBUJACEM','AMRUTANJAN','ANURAS','APARINDS',
                'APLAPOLLO','APLLTD','APOLLOHOSP','APOLLOPIPE','APOLLOTYRE','ARVIND','ARVINDFASN','ASAHIINDIA','ASHIANA',
                'ASHOKA','ASHOKLEY','ASIANPAINT','ASTEC','ASTERDM','ASTRAL','ASTRAZEN','ATFL','ATUL','AUBANK','AUROPHARMA',
                'AUTOAXLES','AVANTIFEED','AXISBANK','BAJAJ-AUTO','BAJAJCON','BAJAJELEC','BAJAJFINSV','BAJAJHLDNG','BAJFINANCE',
                'BALAMINES','BALKRISIND','BALMLAWRIE','BALRAMCHIN','BANARISUG','BANDHANBNK','BANKBARODA','BANKINDIA','BASF',
                'BATAINDIA','BBTC','BDL','BECTORFOOD','BEL','BEML','BEPL','BERGEPAINT','BHARATFORG','BHARATRAS','BHARTIARTL',
                'BHEL','BIOCON','BIRLACORPN','BLUEDART','BLUESTARCO','BOMDYEING','BOSCHLTD','BPCL','BRIGADE','BRITANNIA','BSE',
                'BSOFT','CAMLINFINE','CANBK','CANFINHOME','CAPACITE','CAPLIPOINT','CARBORUNIV','CARERATING','CASTROLIND','CCL',
                'CDSL','CEATLTD','CENTRALBK','CENTRUM','CENTURYPLY','CENTURYTEX','CERA','CESC','CGCL','CHALET','CHAMBLFERT',
                'CHEMCON','CHENNPETRO','CHOLAFIN','CHOLAHLDNG','CIPLA','COALINDIA','COCHINSHIP','COFORGE','COLPAL','CONCOR',
                'CONFIPET','COROMANDEL','CRAFTSMAN','CREDITACC','CRISIL','CROMPTON','CSBBANK','CUB','CUMMINSIND','CYIENT',
                'DAAWAT','DABUR','DALBHARAT','DALMIASUG','DBCORP','DBL','DCAL','DCBBANK','DCMSHRIRAM','DEEPAKNTR','DELTACORP',
                'DEN','DFMFOODS','DHAMPURSUG','DHANI','DHANUKA','DIAMONDYD','DISHTV','DIVISLAB','DIXON','DLF','DMART','DOLLAR',
                'DRREDDY','EASEMYTRIP','EDELWEISS','EICHERMOT','EIDPARRY','EIHOTEL','ELGIEQUIP','EMAMILTD','ENDURANCE',
                'ENGINERSIN','EPL','EQUITAS','EQUITASBNK','ERIS','ESABINDIA','ESCORTS','EVEREADY','EXIDEIND','FACT',
                'FCONSUMER','FDC','FEDERALBNK','FILATEX','FINCABLES','FINEORG','FINPIPE','FMGOETZE','FORTIS','FRETAIL',
                'FSL','GABRIEL','GAEL','GAIL','GALAXYSURF','GANECOS','GARFIBRES','GATI','GENUSPOWER','GEOJITFSL','GEPIL',
                'GESHIP','GET&D','GHCL','GICRE','GILLETTE','GLAND','GLAXO','GLENMARK','GMDCLTD','GMMPFAUDLR','GMRINFRA',
                'GNFC','GODFRYPHLP','GODREJAGRO','GODREJCP','GODREJIND','GODREJPROP','GPPL','GRANULES','GRAPHITE','GRASIM',
                'GREAVESCOT','GREENLAM','GREENPLY','GRINDWELL','GRSE','GSFC','GSPL','GTPL','GUJALKALI','GUJGASLTD','GULFOILLUB',
                'HAL','HAPPSTMNDS','HATHWAY','HATSUN','HAVELLS','HCC','HCG','HCLTECH','HDFC','HDFCAMC','HDFCBANK','HDFCLIFE',
                'HEG','HEIDELBERG','HEMIPROP','HERANBA','HERITGFOOD','HEROMOTOCO','HESTERBIO','HFCL','HGINFRA','HIKAL','HIL',
                'HIMATSEIDE','HINDALCO','HINDCOPPER','HINDOILEXP','HINDPETRO','HINDUNILVR','HINDZINC','HOMEFIRST','HONAUT',
                'HSCL','HUDCO','HUHTAMAKI','IBREALEST','IBULHSGFIN','ICICIBANK','ICICIGI','ICICIPRULI','ICIL','ICRA','IDBI',
                'IDEA','IDFC','IDFCFIRSTB','IEX','IFBIND','IFCI','IGL','IGPL','IIFLSEC','IIFLWAM','IMFA','INDHOTEL','INDIACEM',
                'INDIAGLYCO','INDIAMART','INDIANB','INDIGO','INDIGOPNTS','INDOCO','INDOSTAR','INDUSINDBK','INDUSTOWER',
                'INEOSSTYRO','INFIBEAM','INFY','INGERRAND','INOXLEISUR','INOXWIND','INTELLECT','IOB','IOC','IOLCP','IPCALAB',
                'IRB','IRCON','IRCTC','IRFC','ISEC','ITC','ITDC','ITDCEM','ITI','J&KBANK','JAGRAN','JAICORPLTD','JAMNAAUTO',
                'JBCHEPHARM','JBMA','JCHAC','JINDALPOLY','JINDALSAW','JINDALSTEL','JKCEMENT','JKIL','JKLAKSHMI','JKPAPER',
                'JKTYRE','JMCPROJECT','JMFINANCIL','JPPOWER','JSL','JSLHISAR','JSWHL','JSWSTEEL','JTEKTINDIA','JUBLFOOD',
                'JUBLINGREA','JUBLPHARMA','JUSTDIAL','JYOTHYLAB','KAJARIACER','KALPATPOWR','KALYANKJIL','KANSAINER',
                'KARURVYSYA','KEC','KEI','KIOCL','KIRIINDUS','KIRLOSENG','KIRLOSIND','KNRCON','KOLTEPATIL','KOTAKBANK',
                'KPITTECH','KPRMILL','KRBL','KSB','KSCL','KSL','KTKBANK','L&TFH','LALPATHLAB','LAOPALA','LAURUSLABS',
                'LAXMIMACH','LEMONTREE','LICHSGFIN','LINDEINDIA','LT','LTI','LTTS','LUMAXIND','LUPIN','LUXIND','LXCHEM',
                'M&M','M&MFIN','MAHABANK','MAHINDCIE','MAHLIFE','MAHLOG','MAHSCOOTER','MAHSEAMLES','MAITHANALL','MANAPPURAM',
                'MARICO','MARKSANS','MARUTI','MASFIN','MASTEK','MATRIMONY','MAXHEALTH','MAYURUNIQ','MAZDOCK','MCDOWELL-N',
                'METROPOLIS','MFSL','MGL','MHRIL','MIDHANI','MINDACORP','MINDAIND','MINDTREE','MMFL','MMTC','MOIL','MOREPENLAB',
                'MOTHERSUMI','MOTILALOFS','MPHASIS','MRF','MRPL','MSTCLTD','MTARTECH','MTNL','MUTHOOTFIN','NAM-INDIA',
                'NATCOPHARM','NATIONALUM','NAUKRI','NAVINFLUOR','NAVNETEDUL','NAZARA','NBCC','NBVENTURES','NCC','NEOGEN',
                'NESCO','NETWORK18','NEWGEN','NFL','NH','NHPC','NIACL','NIITLTD','NILKAMAL','NLCINDIA','NMDC','NOCIL','NTPC',
                'NUCLEUS','OAL','OBEROIRLTY','OFSS','OIL','OMAXE','ONGC','ORIENTCEM','ORIENTELEC','ORISSAMINE','PAGEIND',
                'PAISALO','PCJEWELLER','PEL','PERSISTENT','PETRONET','PFC','PFIZER','PGHH','PGHL','PHOENIXLTD','PIDILITIND',
                'PIIND','PILANIINVS','PNB','PNCINFRA','POLYCAB','POLYMED','POLYPLEX','POWERGRID','POWERINDIA','PRAKASH',
                'PRESTIGE','PRINCEPIPE','PRIVISCL','PRSMJOHNSN','PSB','PSPPROJECT','PTC','PURVA','PVR','QUESS','QUICKHEAL',
                'RADICO','RAILTEL','RAIN','RAJESHEXPO','RALLIS','RAMCOCEM','RAMCOIND','RAMCOSYS','RATNAMANI','RAYMOND',
                'RBLBANK','RCF','RECLTD','REDINGTON','RELAXO','RELIANCE','RELIGARE','REPCOHOME','RESPONIND','RITES','RKFORGE',
                'ROSSARI','ROUTE','RSYSTEMS','RUCHI','RUPA','RVNL','SAFARI','SAGCEM','SAIL','SANDHAR','SANOFI','SASKEN',
                'SBICARD','SBILIFE','SBIN','SCHAEFFLER','SCHNEIDER','SCI','SEQUENT','SFL','SHARDACROP','SHILPAMED','SHK',
                'SHOPERSTOP','SHREECEM','SHRIRAMCIT','SIEMENS','SIS','SJVN','SKFINDIA','SOBHA','SOLARA','SOLARINDS',
                'SONATSOFTW','SOTL','SOUTHBANK','SPANDANA','SPARC','SRF','SRTRANSFIN','STAR','STARCEMENT','STLTECH',
                'STOVEKRAFT','SUBEXLTD','SUBROS','SUDARSCHEM','SUMICHEM','SUNCLAYLTD','SUNDARMFIN','SUNDRMFAST','SUNPHARMA',
                'SUNTECK','SUNTV','SUPRAJIT','SUPREMEIND','SURYAROSNI','SURYODAY','SUVENPHAR','SUVIDHAA','SUZLON',
                'SWANENERGY','SWARAJENG','SWSOLAR','SYMPHONY','SYNGENE','TASTYBITE','TATACHEM','TATACOFFEE','TATACOMM',
                'TATACONSUM','TATAELXSI','TATAINVEST','TATAMETALI','TATAMOTORS','TATAPOWER','TATASTEEL','TCI','TCIEXP',
                'TCNSBRANDS','TCS','TEAMLEASE','TECHM','TECHNOE','THERMAX','THOMASCOOK','THYROCARE','TIDEWATER','TIINDIA',
                'TIMETECHNO','TIMKEN','TINPLATE','TITAN','TORNTPHARM','TORNTPOWER','TRENT','TRITURBINE','TRIVENI','TTKPRESTIG',
                'TV18BRDCST','TVSMOTOR','TVSSRICHAK','TVTODAY','UBL','UCOBANK','UFLEX','UJJIVAN','UJJIVANSFB','ULTRACEMCO',
                'UNICHEMLAB','UNIONBANK','UPL','UTIAMC','VAIBHAVGBL','VAKRANGEE','VARROC','VBL','VEDL','VENKEYS','VESUVIUS',
                'VGUARD','VINATIORGA','VIPIND','VMART','VOLTAS','VRLLOG','VSTIND','VSTTILLERS','VTL','WABAG',
                'WELCORP','WELENT','WELSPUNIND','WHIRLPOOL','WIPRO','WOCKPHARMA','WSTCSTPAPR','YESBANK','ZEEL','ZENSARTECH',
                'ZYDUSWELL',]

In [4]:
def oldDate(n):
    return datetime.now() - timedelta(n)
def path(i):
        return f'P:/DEPROJECT/Clean_bhav_copy/Clean_bhavcopy_{oldDate(i).strftime("%Y-%m-%d")}.csv'
def Comapny_file_path(name):
    return f'P:/DEPROJECT/Company_file/{name}.csv'

In [5]:
for i in Company_list:
    df = pd.DataFrame(columns=COLUMN_NAMES)
    df.to_csv(f'P:/DEPROJECT/Company_file/{i}.csv',index=False)

In [6]:
for i in reversed(range(0,40)):
    try:
        df = pd.read_csv(path(i))
        print(oldDate(i).strftime("%Y-%m-%d"))
        for i in Company_list:
            # Loading companys csv file in program 
            company_df = pd.read_csv(Comapny_file_path(i))
            
            # Finding comapnys row from clean bhav copy 
            temp_df = df[df['SYMBOL']== i]

            # Adding companys now to company's csv file 
            company_df = pd.concat([company_df, temp_df], ignore_index = True, axis = 0)

            company_df.drop_duplicates(subset ="DATE",keep = "last", inplace = True,ignore_index= True)    
            company_df.to_csv(Comapny_file_path(i), index=False)
    except:
        print(f'{oldDate(i).strftime("%Y-%m-%d")} --> no data')

2022-04-07
2022-04-08
2022-04-09 --> no data
2022-04-10
2022-04-11
2022-04-12
2022-04-13
2022-04-14
2022-04-15
2022-04-16 --> no data
2022-04-17
2022-04-18
2022-04-19
2022-04-20
2022-04-21
2022-04-22
2022-04-23 --> no data
2022-04-24
2022-04-25
2022-04-26
2022-04-27
2022-04-28
2022-04-29
2022-04-30 --> no data
2022-05-01
2022-05-02
2022-05-03
2022-05-04
2022-05-05
2022-05-06
2022-05-07 --> no data
2022-05-08
2022-05-09
2022-05-10
2022-05-11
2022-05-12
2022-05-13
2022-05-14 --> no data
2022-05-15
2022-05-16 --> no data

In [7]:
company_df = pd.read_csv('Company_file/3MINDIA.csv')
company_df.drop_duplicates(subset ="DATE",keep = "last", inplace = True,ignore_index= True)
display(company_df)

,SYMBOL,SERIES,DATE,PREV_CLOSE,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,LAST_PRICE,CLOSE_PRICE,AVG_PRICE,TTL_TRD_QNTY,NO_OF_TRADES,DELIV_QTY,DELIV_PER,DELIV_VALUE,5DDeVA,%Change_In_Price,%Change_In_Deliv_vs_AVG,Intraday_volume
0,3MINDIA,EQ,07-Apr-2022,21522.00,21555.0,21555.00,20920.00,21134.60,21104.40,21204.80,2781,1190,1712,61.56,NaN,NaN,NaN,NaN,NaN
1,3MINDIA,EQ,08-Apr-2022,21104.40,21222.0,21490.00,21060.00,21411.00,21440.70,21264.84,1338,735,647,48.36,NaN,NaN,NaN,NaN,NaN
2,3MINDIA,EQ,11-Apr-2022,21440.70,21303.0,21550.00,21299.35,21400.00,21493.95,21459.51,2125,847,1580,74.35,NaN,NaN,NaN,NaN,NaN
3,3MINDIA,EQ,12-Apr-2022,21493.95,21400.0,21443.00,21050.00,21201.00,21378.40,21285.02,1948,863,1087,55.80,NaN,NaN,NaN,NaN,NaN
4,3MINDIA,EQ,13-Apr-2022,21378.40,21232.0,21400.00,21200.00,21300.00,21339.95,21274.20,1099,707,642,58.42,NaN,NaN,NaN,NaN,NaN
5,3MINDIA,EQ,18-Apr-2022,21339.95,21300.0,21800.00,20729.85,21688.40,21598.75,21206.53,3299,1607,1945,58.96,NaN,NaN,NaN,NaN,NaN
6,3MINDIA,EQ,19-Apr-2022,21598.75,21699.9,21800.00,21010.00,21021.05,21257.90,21478.40,4248,2978,2741,64.52,NaN,NaN,NaN,NaN,NaN
7,3MINDIA,EQ,20-Apr-2022,21257.90,21380.0,21398.70,20700.20,20730.00,20813.60,20921.26,1922,1267,1057,54.99,NaN,NaN,NaN,NaN,NaN
8,3MINDIA,EQ,21-Apr-2022,20813.60,20767.0,21398.00,20767.00,21216.00,21209.60,21101.91,1384,798,730,52.75,NaN,NaN,NaN,NaN,NaN
9,3MINDIA,EQ,22-Apr-2022,21209.60,21001.0,21324.15,20211.55,20505.00,20481.35,20522.03,4562,2614,2142,46.95,NaN,NaN,NaN,NaN,NaN
10,3MINDIA,EQ,25-Apr-2022,20481.35,20740.0,20740.00,20000.00,20154.10,20165.00,20280.76,2509,1375,800,31.89,NaN,NaN,NaN,NaN,NaN
11,3MINDIA,EQ,26-Apr-2022,20165.00,20388.0,20449.95,19950.00,20029.00,20008.60,20100.09,1700,998,994,58.47,NaN,NaN,NaN,NaN,NaN
12,3MINDIA,EQ,27-Apr-2022,20008.60,20100.0,20100.00,19939.60,19950.00,19968.60,19986.52,1072,541,620,57.84,NaN,NaN,NaN,NaN,NaN
13,3MINDIA,EQ,28-Apr-2022,19968.60,20090.0,20344.00,19900.00,20250.00,20016.95,20001.94,1111,576,718,64.63,NaN,NaN,NaN,NaN,NaN
14,3MINDIA,EQ,29-Apr-2022,20016.95,20190.0,20250.00,19831.00,20020.00,19964.55,20004.82,1191,930,842,70.70,NaN,NaN,NaN,NaN,NaN
15,3MINDIA,EQ,02-May-2022,19964.55,19806.6,20101.00,19600.00,19982.50,19831.10,19895.57,5191,2223,3548,68.35,NaN,NaN,NaN,NaN,NaN
16,3MINDIA,EQ,04-May-2022,19831.10,19950.0,19950.00,18810.25,19011.00,19150.30,19361.85,4062,1875,2489,61.28,NaN,NaN,NaN,NaN,NaN
17,3MINDIA,EQ,05-May-2022,19150.30,19370.0,19443.95,18505.00,18570.05,18545.90,18786.92,3516,2606,1955,55.60,NaN,NaN,NaN,NaN,NaN
18,3MINDIA,EQ,06-May-2022,18545.90,18550.0,18599.95,18100.00,18477.30,18449.95,18246.71,5955,3228,4383,73.60,NaN,NaN,NaN,NaN,NaN
19,3MINDIA,EQ,09-May-2022,18449.95,18540.0,18979.00,17954.95,18750.00,18735.75,18434.59,4659,3144,2442,52.41,NaN,NaN,NaN,NaN,NaN
20,3MINDIA,EQ,10-May-2022,18735.75,18945.0,18945.00,18099.95,18102.25,18106.35,18280.68,5618,3409,3364,59.88,NaN,NaN,NaN,NaN,NaN
21,3MINDIA,EQ,11-May-2022,18106.35,18111.0,18338.00,17650.00,17824.00,17778.60,17888.57,5971,3004,4130,69.17,NaN,NaN,NaN,NaN,NaN
22,3MINDIA,EQ,12-May-2022,17778.60,17760.0,18349.75,17680.00,18058.05,17980.25,17825.71,5251,3332,3661,69.72,NaN,NaN,NaN,NaN,NaN
23,3MINDIA,EQ,13-May-2022,17980.25,18113.7,18500.00,17862.70,17910.00,17988.85,18021.14,2254,1272,1271,56.39,NaN,NaN,NaN,NaN,NaN